import mongoose from 'mongoose'

const RecipeSchema = new mongoose.Schema({
  dateCreated: {
    /* Autogenerated field for the date the recipe was created */
    type: Date,
  },
  submittedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  image: {
    type: String,
  },
  keywords: {
    type: Array,
  },
  recipeCategory: {
    type: Array,
  },
  recipeIngredients: {
    type: Array,
  },
  recipeInstructions: {
    type: String,
  },
  recipeYield: {
    type: String,
  },
  title: {
    type: String,
    required: [true, 'Please provide a title for this recipe.'],
    maxlength: [200, 'Title cannot be more than 200 characters'],
  },
})

export default mongoose.models.Recipe || mongoose.model('Recipe', RecipeSchema)
