import mongoose from 'mongoose'

const IngredientSchema = new mongoose.Schema({
  header: String,
  ingredients: String,
})

const RecipeSchema = new mongoose.Schema({
  complimentaryRecipes: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: 'Recipe',
  },
  cookTime: String,
  datePublished: {
    /* Autogenerated field for the date the recipe was created */
    type: Date,
  },
  description: String,
  image: String,
  keywords: [
    {
      type: String,
      lowercase: true,
      trim: true,
    },
  ],
  name: {
    type: String,
    required: [true, 'Please provide a title for this recipe.'],
    maxlength: [200, 'Title cannot be more than 200 characters'],
  },
  originalSource: String || {
    type: [mongoose.Schema.Types.ObjectId],
    ref: 'Recipe',
  },
  prepTime: String,
  recipeCategory: String,
  recipeCuisine: String,
  recipeIngredient: [String],
  ingredients: [IngredientSchema],
  recipeInstructions: String,
  recipeYield: String,
  similarRecipes: [
    {
      type: [mongoose.Schema.Types.ObjectId],
      ref: 'Recipe',
    },
  ],
  submittedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  suitableForDiet: [String],
  totalTime: String,
  untested: Boolean,
})

export default mongoose.models.Recipe || mongoose.model('Recipe', RecipeSchema)
