import mongoose from 'mongoose'

const IngredientSchema = new mongoose.Schema({
  header: String,
  recipeIngredient: [String],
})

const NutritionSchema = new mongoose.Schema({
  calories: String,
  carbohydrateContent: String,
  cholesterolContent: String,
  fatContent: String,
  fiberContent: String,
  proteinContent: String,
  saturatedFatContent: String,
  servingSize: String,
  sodiumContent: String,
  sugarContent: String,
  transFatContent: String,
  unsaturatedFatContent: String,
})

const StepSchema = new mongoose.Schema({
  text: String,
  url: String,
})

const RecipeSchema = new mongoose.Schema({
  author: {},
  complimentaryRecipes: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: 'Recipe',
  },
  cookTime: String,
  datePublished: {
    /* Autogenerated field for the date the recipe was created */
    type: Date,
  },
  description: String,
  image: String,
  keywords: [
    {
      type: String,
      lowercase: true,
      trim: true,
    },
  ],
  name: {
    type: String,
    required: [true, 'Please provide a title for this recipe.'],
    maxlength: [200, 'Title cannot be more than 200 characters'],
  },
  nutrition: NutritionSchema,
  prepTime: String,
  recipeCategory: String,
  recipeCuisine: String,
  recipeIngredients: [IngredientSchema],
  recipeInstructions: [StepSchema],
  recipeYield: String,
  similarRecipes: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: 'Recipe',
  },
  submittedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  suitableForDiet: [String],
  totalTime: String,
})

export default mongoose.models.Recipe || mongoose.model('Recipe', RecipeSchema)
